* Definitions for the order application, as DFHCSDUP reads them:
* commands over several lines, values with spaces and parentheses,
* and commands other than DEFINE, which are passed over.
 DEFINE TRANSACTION(ORD1) GROUP(ORDERS)
        PROGRAM(ORDMENU) TWASIZE(0) PROFILE(DFHCICST)
 DEFINE PROGRAM(ORDMENU) GROUP(ORDERS) LANGUAGE(COBOL)
        DESCRIPTION(ORDER MENU (MAIN SCREEN))
 DEFINE PROGRAM(ORDENTRY) GROUP(ORDERS)
 DEFINE MAPSET(ORDSET) GROUP(ORDERS)
 DEFINE FILE(ORDFILE) GROUP(ORDERS) DSNAME(PROD.ORDERS.KSDS)
        RECORDFORMAT(V),ADD(YES),BROWSE(YES)
 DEFINE TDQUEUE(ORDQ) GROUP(ORDERS)
 ADD GROUP(ORDERS) LIST(ORDLIST)
 LIST GROUP(ORDERS)
 DEFINE TRANSACTION(ORD2) GROUP(ORDERS) PROGRAM(ORDENTRY)
